# Generated by Django 2.2.12 on 2021-05-20 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ask_title', models.CharField(max_length=200, verbose_name='Вопрос')),
                ('asker_name', models.CharField(max_length=50, verbose_name='Имя спрашивающего')),
                ('ask_explane', models.TextField(verbose_name='Пояснение вопроса')),
                ('ask_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('ask_tags', models.CharField(max_length=50, verbose_name='Тег')),
                ('ask_answers', models.IntegerField(verbose_name='Кол-во ответов')),
                ('ask_rating', models.IntegerField(verbose_name='Рейтинг вопроса')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_login', models.CharField(max_length=20, verbose_name='Имя пользователя')),
                ('user_email', models.CharField(max_length=50, verbose_name='Емейл')),
                ('user_password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('user_avatar', models.ImageField(upload_to='', verbose_name='Аватарка')),
                ('user_rating', models.IntegerField(verbose_name='Рейтинг')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerer_name', models.CharField(max_length=50, verbose_name='Имя автора')),
                ('answer_text', models.TextField(verbose_name='Текст ответа')),
                ('answer_date', models.DateTimeField(verbose_name='Дата ответа')),
                ('answer_likes', models.IntegerField(verbose_name='Кол-во лайков')),
                ('ask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asking.Ask')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
