# Generated by Django 2.2.12 on 2021-05-17 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ask_title', models.CharField(max_length=200, verbose_name='Вопрос')),
                ('ask_explane', models.TextField(verbose_name='Пояснение вопроса')),
                ('pub_date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name='Имя автора')),
                ('answer_text', models.TextField(verbose_name='Текст ответа')),
                ('ask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asking.Ask')),
            ],
        ),
    ]
