# Generated by Django 2.2.12 on 2021-05-20 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asking', '0002_auto_20210520_2132'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='User',
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50, verbose_name='Tag')),
                ('tag_rating', models.IntegerField(verbose_name='Популярность тега')),
                ('ask_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asking.Ask')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes_count', models.IntegerField(verbose_name='Кол-во лайков')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asking.Answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asking.User')),
            ],
        ),
    ]
