# Generated by Django 2.2.12 on 2021-05-24 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asking', '0005_auto_20210523_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ask',
            name='ask_answers',
        ),
    ]
