# Generated by Django 2.2.12 on 2021-05-24 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asking', '0006_remove_ask_ask_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='ask',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ask_answer', to='asking.Ask'),
        ),
    ]
