# Generated by Django 2.2.12 on 2021-05-24 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asking', '0007_auto_20210524_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answerer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ask_answer', to='asking.Ask'),
        ),
    ]
