# Generated by Django 2.2.12 on 2021-05-25 13:19

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('asking', '0008_auto_20210524_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ask',
            name='ask_tags',
        ),
        migrations.AddField(
            model_name='ask',
            name='ask_tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
