# Generated by Django 2.2.12 on 2021-05-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asking', '0011_auto_20210525_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_is_right',
            field=models.BooleanField(default=False, verbose_name='Правильный ответ'),
        ),
    ]
