# Generated by Django 2.2.12 on 2021-05-28 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asking', '0013_auto_20210526_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerlike',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_like', to='asking.Answer'),
        ),
        migrations.AlterField(
            model_name='asklike',
            name='ask',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ask_like', to='asking.Ask'),
        ),
    ]
