# Generated by Django 2.2.12 on 2021-05-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asking', '0014_auto_20210528_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_dislikes',
            field=models.IntegerField(default=0, verbose_name='Кол-во лайков'),
        ),
        migrations.AddField(
            model_name='ask',
            name='ask_dislikes',
            field=models.IntegerField(default=0, verbose_name='Кол-во лайков'),
        ),
        migrations.AddField(
            model_name='ask',
            name='ask_likes',
            field=models.IntegerField(default=0, verbose_name='Кол-во лайков'),
        ),
    ]
