# Generated by Django 2.2.12 on 2021-05-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asking', '0017_auto_20210531_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='asking/img/', verbose_name='Аватарка'),
        ),
    ]
